-- 코드를 입력하세요
SELECT A.AUTHOR_ID,
A.AUTHOR_NAME,
B.CATEGORY,
SUM(B.PRICE * BS.SALES) AS TOTAL_SALES

FROM AUTHOR A JOIN BOOK B
        ON A.AUTHOR_ID = B.AUTHOR_ID
    JOIN BOOK_SALES BS
        ON B.BOOK_ID = BS.BOOK_ID

WHERE DATE_FORMAT(BS.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;