-- ECOLI_DATA: ID, PARENT_ID, 
-- SUBQUERY나 CTE로 각 세대를 지정해주면 될 거 같아요

WITH RECURSIVE GENERATION AS (
    SELECT ID, 1 AS GEN
    FROM ECOLI_DATA E1
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, G.GEN + 1 AS GEN
    FROM ECOLI_DATA E JOIN GENERATION G
    WHERE E.PARENT_ID = G.ID
            AND E.PARENT_ID IS NOT NULL
)
SELECT ID
FROM GENERATION
WHERE GEN = 3
ORDER BY ID