-- ITEM 업그레이드 A B C 순서로, A는 B의 PARENT
-- ITEM_INFO: ID, NAME, PARITY, PRICE
-- ITEM_TREE: ID, PARENT ID
-- LEAF노드를 구하라는 거 같고요 
-- ITEM_ID, ITEM_NAME, PARITY 

-- INFO의 ID가 TREE의 PRAENT_ID에 포함되지 않을 때 
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN (SELECT PARENT_ITEM_ID
                     FROM ITEM_TREE
                     WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY ITEM_ID DESC
