-- 코드를 입력하세요
-- ONLINE_SALE / OFFLINE_SALE
-- 오프라인, 온라인 판매 날짜, 상품ID, 유저ID, 판매량
-- 오프라인만 USER_ID는 NULL으로
-- 판매일 상품ID기준 ASC / 같으면 유저ID ASC
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
PRODUCT_ID,
USER_ID,
SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE LIKE ('2022-03%')
UNION
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
PRODUCT_ID, 
NULL AS USER_ID,
SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE LIKE ('2022-03%') 
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID