-- ANIMAL_INS: ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME, SEX_UPON_INTAKE
-- ANIMAL_OUTS: ANIMAL_ID, ANIMAL_TYPE, DATETIME, NAME, SEX_UPON_OUTCOME
-- ANIMAL_INS에는 SEX LIKE 'Intact' OUTS에는 'Spayed'인 동물을
-- id, type, name을 order by id

SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME
FROM
    ANIMAL_INS INS
    JOIN ANIMAL_OUTS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE SEX_UPON_INTAKE LIKE 'Intact%' 
    AND (SEX_UPON_OUTCOME LIKE 'Spayed%' 
         OR SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY ANIMAL_ID