-- USER_INFO: USER_ID, GENDER, AGE, JOINED 
-- GENDER는 0 남자 1 여자
-- ONLINE_SALE: ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
-- (SALES_DATE, USER_ID, PRODUCT_ID) 

-- 연/월/성별 
-- ORDER BY 년/월/성별 ASC
-- 성별이 없으면 -> 결과에서 제외 (WHERE GENDER IS NOT NULL)
SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT OS.USER_ID) AS USERS
FROM ONLINE_SALE OS JOIN USER_INFO UI
    ON OS.USER_ID = UI.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
