-- CAR_RENTAL_COMPANY_RENTAL_HISTORY: HISTORY_ID, CAR_ID, START_DATE, END_DATE
-- CAR_ID로 GROUP BY 를 했을 때 AVG(END_DATE - START_DATE) AS AVERAGE_DURTAION
-- 평균값을 ROUND(,2) 
-- AVERAGE_DURATION DESC, CAR_ID DESC
# SELECT CAR_ID, START_DATE, END_DATE, DATEDIFF(END_DATE, START_DATE)
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY

SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC