-- FISH_INFO: ID, FISH_TYPE, LENGTH, TIME
-- LENGTH < 10 이면 NULL임.
-- FISH_NAME_INFO: FISH_TYPE, FISH_NAME

-- 물고기 종류 별 이름과 잡은 수
-- 잡은 수 기준 내림차순

SELECT SUM(CASE WHEN FI.FISH_TYPE IS NOT NULL THEN 1
          ELSE 0 END) AS FISH_COUNT,
        FISH_NAME
FROM FISH_NAME_INFO FNI JOIN FISH_INFO FI
    ON FNI.FISH_TYPE = FI.FISH_TYPE
GROUP BY FISH_NAME
ORDER BY FISH_COUNT DESC