-- ECOLI_DATA: ID, PARENT_ID, SIZE_OF_COLONY, DIFFERENTIATION_DATE, GENOTYPE 
-- ID와 PARENT_ID로 세대부터 정렬하면 좋을 거 같습니다
-- ID가 PARENT_ID 목록에 있으면 자식이 있는 거고 없으면 없는 거니까
-- CASE WHEN ID IN (SELECT PARENT_IF FROM ECOLI_DATA) SUM을 하면 될 거 같음
-- PARENT_ID가 NULL이면 1이고 
-- RECURSIVE 문으로 GENERATION + 1 하면 될 거 같다

WITH RECURSIVE RECURSIVE_GEN AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1 AS GENERATION
    FROM RECURSIVE_GEN G JOIN ECOLI_DATA E
            ON E.PARENT_ID = G.ID
)
SELECT COUNT(*) AS 'COUNT',
        GENERATION
FROM RECURSIVE_GEN
WHERE ID NOT IN (SELECT PARENT_ID FROM ECOLI_DATA
                WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION