-- CAR_RENTAL_COMPANY_RENTAL_HISTORY: HISTORY_ID, CAR_ID, START_DATE, END_DATE
-- 2022년 10월 16일에 대여 중이면 -> '대여중', 아니면 -> '대여 가능' AS AVAILABILITY
-- 반납일이 22-10-16 '대여중'
-- ORDER BY CAR_ID DESC

-- CTE CASE WHEN 으로 대여중이면 1, 대여가능이면 0 -> SUM(CASE WHEN) > 0 대여중
-- GROUP BY CAR_ID
-- 
WITH IS_AVALABLE AS (
    SELECT HISTORY_ID, CAR_ID, END_DATE,
        SUM(CASE 
            WHEN START_DATE = '2022-10-16' THEN 1
            WHEN START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16' THEN 1
                ELSE 0 END) AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
)
SELECT CAR_ID, 
        CASE WHEN AVAILABILITY > 0 THEN '대여중'
            WHEN AVAILABILITY = 0 THEN '대여 가능'
            END AS AVAILABILITY
FROM IS_AVALABLE
ORDER BY CAR_ID DESC