-- SIZE_OF_COLONY가 100 이하면 LOW 1000 이하면 MEDIUM 1000 초과면 HIGH
-- ID와 SIZE 출력

SELECT ID, IF (SIZE_OF_COLONY <= 100, 'LOW',
               IF (SIZE_OF_COLONY <= 1000, 'MEDIUM', 'HIGH')) AS SIZE
FROM ECOLI_DATA
ORDER BY ID