-- ECOLI_DATA: ID, PARENT_ID, SIZE_OF_COLONY, DIFFERENTIATION_DATE, GENOTYPE
-- QUARTER별 분화된 대장균 개체의 총 수 출력
-- 각 분기는 Q를 붙이고 분기에 대해 오름차순 정렬
-- 아... 123 / 456 / 789 / 101112 이렇게 4분기 ㅇㅋㅇㅋ
-- CASE WHEN DIFFERENTIATION_DATE MONTH로 분기 ㅋㅋ 흠;; 부모자식도 아니네요

SELECT
    CASE WHEN MONTH(DIFFERENTIATION_DATE) IN (1, 2, 3) THEN '1Q'
        WHEN MONTH(DIFFERENTIATION_DATE) IN (4, 5, 6) THEN '2Q'
        WHEN MONTH(DIFFERENTIATION_DATE) IN (7, 8, 9) THEN '3Q'
        WHEN MONTH(DIFFERENTIATION_DATE) IN (10, 11, 12) THEN '4Q'
        END AS QUARTER,
    COUNT(ID) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY 1
ORDER BY 1