-- FOOD_PRODUCT: PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
-- FOOD_ORDER: ORDER_ID, PRODUCT_ID, AMOUNT, PRODUCE_DATE, IN_DATE, OUT_DATE, FACTORY_ID, WAREHOUSE_ID

-- 생산일자 = 2022년 05월 
-- PRODUCT_ID, PRODUCT_NAME, TOTAL_SALES
-- ORDER BY TOTALPRICE DESC, PRODUCT_ID

SELECT 
    FO.PRODUCT_ID, PRODUCT_NAME,
    SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FP 
    JOIN FOOD_ORDER FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY FP.PRODUCT_ID
ORDER BY 3 DESC, 1 ASC
