-- PATIENT: PT_NO, PT_NAME, GEND_CD, AGE, TLNO
-- DOCTOR: DR_NAME, DR_ID, LCNS_NO, HIRE_YMDM MCDP_CD, TLNO
-- APPOINTMENT: APNT_YMD, APNT_NO, PT_NO, MCDP_CD, MDDR_ID, APNT_CNCL_YN, APNT_CNCL_YMD

-- 2022년 04월 13일 APNT_CNCL_YN = N인 흉부외과(CS)의 진료 예약 내역
-- APNT_NO, PT_NAME, MCDP_CD, DR_NAME, APNT_YMD
-- ORDER BY APNT_YMD ASC

-- APPOINTMENT -> DOCTOR -> PATIENT
SELECT APNT_NO, PT_NAME, AP.PT_NO, D.MCDP_CD, DR_NAME, APNT_YMD
FROM 
    APPOINTMENT AP
    LEFT JOIN DOCTOR D ON AP.MDDR_ID = D.DR_ID AND AP.MCDP_CD = D.MCDP_CD
    JOIN PATIENT P ON AP.PT_NO = P.PT_NO
WHERE 
    DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' 
    AND APNT_CNCL_YN = 'N' 
    AND AP.MCDP_CD = 'CS'
ORDER BY APNT_YMD ASC