-- SKILLCODES: NAME, CATEGORY, CODE(2제곱)
-- DEVELOPERS: ID, FIRST_NAME, LAST_NAME, EMAIL, SKILL_CODE(CODE의 합)

-- SKILLCODES의 CATEGORY = 'Front End'인 CODE의 합이
-- DEVELOPERS의 SKILL_CODE와 동일하다면
-- SKILL_CODE보다 작으면서 가장 큰 CODE를 빼자
-- 여기에 Front End가 하나라도 포함되면 FE 스킬이 있는 것

-- 아니면 2진수니까 
-- & 연산을 해서
-- CATEGORY = 'Front End'인 CODE와 & 연산한 게 동일하면 ㅇㅇ

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D, SKILLCODES S
WHERE CATEGORY = 'Front End'
    AND SKILL_CODE & CODE = CODE
GROUP BY ID, EMAIL, FIRST_NAME, LAST_NAME
ORDER BY ID