-- 코드를 입력하세요
SELECT US.USER_ID, US.NICKNAME, SUM(BD.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD BD, USED_GOODS_USER US
WHERE BD.WRITER_ID = US.USER_ID AND STATUS='DONE'
GROUP BY US.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES