-- MEMBER_PROFILE
-- REST_REVIEW
-- JOIN

-- 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
-- P.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE
-- DATE ASC, TEXT ASC

-- REVIEW 테이블에서 GROUP BY M_ID 했을 때의 COUNT
-- CTE문으로 MEMBER_ID랑 COUNT() 
-- 바깥쪽의 WHERE절에서 CTE.MEMBER_ID = PROFILE.MEMBER_ID
-- 그 사람의 이름, 텍스트, 날짜 

WITH MAX_REVIEWER AS (
    SELECT MEMBER_ID, COUNT(*) AS REVIEW_CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY REVIEW_CNT DESC
    LIMIT 1
)
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, 
        DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MP JOIN REST_REVIEW RR
        ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE RR.MEMBER_ID = (SELECT MEMBER_ID FROM MAX_REVIEWER) -- 가장 리뷰를 많이 작성한 사람과 아이디 동일할 때
ORDER BY 3, 2