SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT IT.ITEM_ID FROM ITEM_TREE IT
                 JOIN ITEM_INFO II
                 ON IT.PARENT_ITEM_ID = II.ITEM_ID
                 WHERE RARITY = 'RARE')
ORDER BY ITEM_ID DESC