-- CAR_RENTAL_COMPANY_RENTAL_HISTORY: HISTORY_ID, CAR_ID, START_DATE, END_DATE
-- START_DATE를 기준으로 22-08 ~ 22-10 대여 횟수가 >= 5 인 자동차들
-- 기간 동안의 MONTH(START_DATE), CAR_ID별 대여 횟수 
-- ORDER BY MONTH(), CAR_ID DESC
WITH CTE AS (
    SELECT
        CAR_ID,
        COUNT(*) AS CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
SELECT
    MONTH(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
        AND CAR_ID IN (SELECT CAR_ID FROM CTE)
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH(START_DATE), CAR_ID DESC