SELECT ID, FISH_NAME, LENGTH
FROM (SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH,
     RANK() OVER(PARTITION BY FI.FISH_TYPE
                ORDER BY FI.LENGTH DESC) AS L_RANK
     FROM FISH_INFO FI
      JOIN FISH_NAME_INFO FNI
      ON FI.FISH_TYPE = FNI.FISH_TYPE) AS RANK_FISH
WHERE L_RANK = 1
ORDER BY ID;