-- USER_GOODS_BOARD: BOARD_ID, WRITER_ID, TITLE, CONTENTS, PRICE, CREATED_DATE, STATUS, VIEWS
-- USER_GOODS_FILE: FILE_ID, FILE_EXT, FILE_NAME, BOARD_ID
-- 조회수가 가장 높은 게시물에 대한 첨부파일 경로 
-- FILE_ID DESC 
-- /home/grep/src/BOARD_ID/FILE_ID+FILE_NAME+FILE_EXT AS FILE_PATH

-- BOARD에서 VIEW DESC LIMIT 1
-- FILE의 BOARD_ID랑 동일하면 PATH를 만드는 식으로
WITH BEST_VIEW AS (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)
SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE 
WHERE BOARD_ID = (SELECT BOARD_ID
                 FROM BEST_VIEW)
ORDER BY FILE_ID DESC